### ISSUE TITLE
Remove platform specific project files

### ISSUE THREAD

**Issue by pattacini** [robotology/human-sensing#1]
@rezaahmadzadeh 
we don't commit project files that are platform specific (e.g. Visual Studio `*.sln` files). Consider cleaning up the repo.

Also the directory name `exe` is too window-ish...

**Comment by alecive** [comment]
@rezaahmadzadeh take a look at this: https://github.com/robotology/funny-things

The structure I always use is this (obviously, take this with a grain of salt, everyone has his own preferences):

```
/root
    CMakeLists.txt
    /app
        CMakeLists.txt
        /conf
        /scripts
    /build (aka "where all the sh*t happens" - NOT VERSIONED)
    /lib (if needed)
        CMakeLists.txt
        /include
        /src
    /modules (or src)
        CMakeLists.txt
        /module1
            CMakeLists.txt
            /include
            /src
        /module2
            CMakeLists.txt
            /include
            /src
```

**Comment by rezaahmadzadeh** [comment]
@pattacini removed platform specific files.
@alecive tried to get the nearest similarity ;) tnx!

**Comment by pattacini** [comment]
Great, thanks.
