### ISSUE TITLE
openpose doesn't compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by vvasco** [robotology/human-sensing#11]
I tried to compile OpenPose on Ubuntu 18.04, but I get the following error:

![error-openpose](https://user-images.githubusercontent.com/9716288/49443212-24f19000-f7cc-11e8-84fc-dfb5e75832d7.png)

Cuda version: cuda 9.1
Cudnn version: cudnn 7.3.1

According to the [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#installation) documentation, OpenPose has been tested extensively with CUDA 8.0 and cuDNN 5.1, which are not available for Ubuntu 18.04.

cc @vtikha @pattacini

**Comment by vtikha** [comment]
@vvasco can you please run `gcc --version` and let us know which version is installed?

**Comment by vvasco** [comment]
7.3.0

**Comment by vtikha** [comment]
Can you try something quick and dirty? 

Can you modify the `../include/crt/host_config.h:119` in your case from >6 to >8.

Another option would be to install gcc6 this way:

`sudo apt install gcc-6 g++-6`
`sudo ln -s /usr/bin/gcc-6 /usr/local/cuda/bin/gcc `
`sudo ln -s /usr/bin/g++-6 /usr/local/cuda/bin/g++ `

**Comment by vvasco** [comment]
The quick and dirty solution worked.
I'll try also the second one and let you know.

**Comment by vtikha** [comment]
Ok leave out the second one. It might create some issues

**Comment by vvasco** [comment]
Thanks @vtikha

**Comment by pattacini** [comment]
Apparently, this workaround created serious conflicts on the CUDA machine of the R1-mk2 setup (if I'm not wrong).
@mbrunettini is about to reinstall the machine.

cc @vtikha @randaz81 @vvasco @Arya07

**Comment by randaz81** [comment]
> Apparently, this workaround created serious conflicts on the CUDA machine of the R1-mk2 setup (if I'm not wrong).
> @mbrunettini is about to reinstall the machine.

I'm not sure if this applies to that specific machine, but please remember that **Installing gcc-6 on Ubuntu18 is absolutely to avoid**, many other packets depends on gcc>7.0, and this operation may break the system! Please use the default packets provided for your ubuntu distro, always.

**Comment by vtikha** [comment]
In theory only the first option was made, eg replacing one line in the host_config which does not install gcc. The second option to install gcc was then redeemed potentially problematic see previous post. If gcc 6 was installed for this issue then it was indeed a mistake, otherwise it has been installed in another occasion.

**Comment by vvasco** [comment]
Hi all, I just want to specify that this issue was related to a problem I had on my machine, so the first option proposed by @vtikha was done there and not on the CUDA machine of the R1-mk2 setup.

**Comment by pattacini** [comment]
Sorry, I linked two facts that were unrelated: what I heard from @randaz81 and this issue.
