### ISSUE TITLE
dlib compilation

### ISSUE THREAD

**Issue by BrutusTT** [robotology/human-sensing#4]
Hi,

I just found out that the CLMH is running slow if the CMAKE_BUILD_TYPE is not set to "Release". If it is unset (default case) the included thirdparty library dlib does not get compiled as Release either and therefore the CLM modules are running incredibly slow. Not sure if this is intended. 

However, as a user I would expect that included thirdparty libraries will be compiled as Release and only get compiled as Debug with an explicit flag. This allows to keep the package in Debug mode while not have to bother to go "too deep" with debugging.

Anyway, if somebody experiences slow CLM behavior that might be the something to look into it.

**Comment by pattacini** [comment]
Right on this topic, by using the `icub-contrib-common` cmake helpers it is straightforward to change the default build type to `Release`.

Actually, `human-sensing` should already make use of those helpers in the correct way. If that's not the case, it's a bug (although minor...)

**Comment by vtikha** [comment]
Closing this as I am currently re-organising the repo and dlib is now being correctly installed.
