### ISSUE TITLE
Move to OpenFace

### ISSUE THREAD

**Issue by alecive** [robotology/human-sensing#9]
Just FYI, CLM is not actively supported or maintained any more. The developers move to a new repository, called OpenFace (https://github.com/cmusatyalab/openface), so I think that it would be worth linking against that rather than CLM.

As far as I know , it should not be a big effort. Feel free to close if nobody is going to take care of this :)

**Comment by vtikha** [comment]
@alecive thanks for the heads up, will include it when migrating software from the `under-review` branch. I have added it to the `to-do` list on the project page.

**Comment by vtikha** [comment]
I am closing this as this issues will be generated automatically from the project list.
